"""Configuration layer -- YAML/JSON config models, merge overlays, API key helpers."""

from .settings import (
    AppConfig,
    ConfigError,
    HookOptions,
    McpServerConfig,
    McpTransport,
    OrchestrationMode,
    PermissionMode,
    PermissionRuleConfig,
    PluginOptions,
    ProviderConfig,
    RuntimeOptions,
    SandboxOptions,
    ToolOptions,
    VscodeOptions,
    add_mcp_server_to_config,
    app_config_from_dict,
    discover_config_paths,
    ensure_default_config,
    get_saved_api_key,
    load_app_config,
    mcp_server_from_dict,
    remove_mcp_server_from_config,
    resolve_config_path,
    set_api_key,
)
from .simple_yaml import YamlError, dump_yaml, load_yaml

__all__ = [
    "AppConfig",
    "ConfigError",
    "HookOptions",
    "McpServerConfig",
    "McpTransport",
    "OrchestrationMode",
    "PermissionMode",
    "PermissionRuleConfig",
    "PluginOptions",
    "ProviderConfig",
    "RuntimeOptions",
    "SandboxOptions",
    "ToolOptions",
    "VscodeOptions",
    "YamlError",
    "add_mcp_server_to_config",
    "app_config_from_dict",
    "discover_config_paths",
    "dump_yaml",
    "ensure_default_config",
    "get_saved_api_key",
    "load_app_config",
    "load_yaml",
    "mcp_server_from_dict",
    "remove_mcp_server_from_config",
    "resolve_config_path",
    "set_api_key",
]
